/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "primary-fixed-dim": "#b6c4ff",
        "secondary-fixed": "#d3e4fe",
        "surface-container-low": "#f2f4f6",
        "primary-container": "#1e3a8a",
        "primary-fixed": "#dce1ff",
        "primary": "#00236f",
        "tertiary-container": "#384055",
        "on-primary-container": "#90a8ff",
        "surface-variant": "#e0e3e5",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#131b2e",
        "surface-bright": "#f7f9fb",
        "secondary": "#505f76",
        "on-surface-variant": "#444651",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00164e",
        "on-secondary-container": "#54647a",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        "on-tertiary-container": "#a4acc5",
        "tertiary": "#222a3e",
        "on-primary-fixed-variant": "#264191",
        "tertiary-fixed-dim": "#bec6e0",
        "outline": "#757682",
        "on-secondary-fixed": "#0b1c30",
        "on-error-container": "#93000a",
        "secondary-container": "#d0e1fb",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "outline-variant": "#c5c5d3",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b6c4ff",
        "on-error": "#ffffff",
        "surface-tint": "#4059aa",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "gutter": "16px",
        "xl": "32px",
        "sm": "8px",
        "lg": "24px",
        "xs": "4px",
        "margin": "24px",
        "base": "4px"
      },
      fontFamily: {
        "sans": ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
